import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import Background3D from "@/components/Background3D";
import BinaryRain from "@/components/BinaryRain";

const stack = [
  ["Frontend", "React 18, TypeScript 5, Vite 5, Tailwind CSS, Framer Motion, Three.js via @react-three/fiber and @react-three/drei"],
  ["Backend", "Lovable Cloud backend function classify-intent implemented as a Deno HTTP function"],
  ["AI / ML", "Gemini 3 Flash Preview through Lovable AI Gateway for live structured intent classification; all-MiniLM-L6-v2 is documented as the recommended embedding model for a production vector encoder"],
  ["Client data flow", "InputStage → EmbeddingStage → EncryptionStage → TransmissionStage → ProcessingStage → DecryptionStage → OutputStage → HackerStage"],
  ["Deployment", "Vite static frontend; managed cloud backend functions; no containers are defined in the repository"],
];

const features = [
  {
    name: "Secure text terminal",
    modules: "InputStage, Index state machine",
    flow: "Plaintext user input → local React state → pipeline transition",
    details: "The input is captured in the browser and retained only as component state. In the current implementation, the plaintext is later sent to the classification backend at the output stage for real ML inference; the FHE path is a research-grade visualization rather than executable cryptography.",
  },
  {
    name: "384-dimensional embedding visualization",
    modules: "EmbeddingStage",
    flow: "Text → simulated 384-D vector bars → progress-complete event",
    details: "The UI animates 24 sampled dimensions representing a 384-dimensional sentence embedding. A production implementation would invoke sentence-transformers/all-MiniLM-L6-v2 before encryption and pass only the resulting vector into the FHE layer.",
  },
  {
    name: "CKKS encryption chamber",
    modules: "EncryptionStage",
    flow: "Embedding vector → CKKS encoding → ciphertext object → noise-budget telemetry",
    details: "The stage models polynomial encoding, approximate-number encryption, ciphertext creation, scale 2^40, polynomial modulus degree 8192, and decreasing noise budget. Values are visual parameters, not generated by an FHE runtime in this app.",
  },
  {
    name: "Encrypted transmission and breach simulation",
    modules: "TransmissionStage, HackerStage, BinaryRain",
    flow: "Ciphertext packet → network traversal → failed adversarial inspection",
    details: "The transmission stage visualizes ciphertext movement through a secure network. Hacker view deliberately exposes only unreadable ciphertext-like fragments and access-denied states.",
  },
  {
    name: "Encrypted neural inference visualization",
    modules: "ProcessingStage",
    flow: "Encrypted vector → linear layers → polynomial sigmoid approximation → encrypted logits",
    details: "The neural core shows FHE-compatible operations: additions, multiplications by plaintext weights, ciphertext-ciphertext products, and polynomial activation approximation. The displayed sigmoid equation explains why nonlinear activations must be approximated in FHE.",
  },
  {
    name: "ML-powered intent output",
    modules: "OutputStage, classify-intent backend function, Supabase client integration",
    flow: "Input text → backend ML classification → sentiment, intent, confidence, response",
    details: "The backend uses a structured tool-calling response to return intent, sentiment, confidence, and a concise assistant response. OutputStage handles loading, errors, fallback analysis, and final rendering.",
  },
];

const endpoints = [
  {
    method: "POST",
    path: "/functions/v1/classify-intent",
    request: `{
  "input": "i am hungry"
}`,
    response: `{
  "intent": "Physiological Need",
  "confidence": 0.94,
  "sentiment": "Neutral",
  "response": "It sounds like your body needs food soon..."
}`,
  },
];

const fheCode = `// Conceptual CKKS pipeline; not executed by the current UI
const context = new CKKSContext({
  polyModulusDegree: 8192,
  coeffModulusBits: [60, 40, 40, 60],
  scale: 2 ** 40,
});

const keys = context.keygen();
const plaintext = context.encoder.encode(embedding384, context.scale);
const ciphertext = context.encryptor.encrypt(plaintext, keys.publicKey);

const z1 = evaluator.matmulPlain(ciphertext, W1);
const a1 = evaluator.polyval(z1, [0.5, 0.25, 0, -1 / 48]);
const logits = evaluator.matmulPlain(a1, W2);

const decrypted = context.decryptor.decrypt(logits, keys.secretKey);
const scores = context.encoder.decode(decrypted);`;

const transformerCode = `from sentence_transformers import SentenceTransformer
import numpy as np

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
text = "i am hungry"
embedding = model.encode(text, normalize_embeddings=True)
assert embedding.shape == (384,)

# In production: encrypt embedding before remote inference
encrypted_vector = ckks_encrypt(embedding.astype(np.float64))`;

const vectorDbCode = `-- Relational schema with pgvector-style storage for production
CREATE TABLE documents (
  id UUID PRIMARY KEY,
  content TEXT NOT NULL,
  embedding VECTOR(384) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX documents_embedding_hnsw
ON documents USING hnsw (embedding vector_cosine_ops);`;

const queryCode = `SELECT id, content, 1 - (embedding <=> :query_embedding) AS cosine_similarity
FROM documents
ORDER BY embedding <=> :query_embedding
LIMIT 8;`;

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="scroll-mt-24 border-t border-border/70 py-10">
      <h2 className="mb-6 text-xl text-vault-cyan vault-glow-cyan md:text-2xl">{title}</h2>
      <div className="space-y-5 text-sm leading-7 text-foreground/90 md:text-base">{children}</div>
    </section>
  );
}

function CodeBlock({ children }: { children: string }) {
  return (
    <pre className="overflow-x-auto rounded-lg border border-border bg-background/80 p-4 text-xs leading-6 text-vault-cyan shadow-inner md:text-sm">
      <code>{children}</code>
    </pre>
  );
}

export default function TechnicalReport() {
  return (
    <main className="relative min-h-screen">
      <Background3D />
      <BinaryRain />
      <div className="relative z-10 mx-auto max-w-6xl px-4 py-8 md:px-8">
        <nav className="mb-8 flex items-center justify-between gap-4">
          <Link to="/" className="vault-button px-4 py-2 text-xs">← Pipeline</Link>
          <span className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Vault Infer / Engineering Report</span>
        </nav>

        <motion.header initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="mb-12">
          <p className="mb-3 font-mono text-xs uppercase tracking-widest text-vault-cyan">Research-grade system documentation</p>
          <h1 className="max-w-5xl text-3xl text-primary vault-glow md:text-5xl">Vault Infer Technical Documentation Report</h1>
          <p className="mt-5 max-w-4xl text-sm leading-7 text-muted-foreground md:text-base">
            This report documents the implemented cinematic web system and explicitly distinguishes shipped code from cryptographic and vector-database assumptions required for a production FHE deployment.
          </p>
        </motion.header>

        <div className="grid gap-8 lg:grid-cols-[250px_1fr]">
          <aside className="hidden lg:block">
            <div className="sticky top-6 vault-panel p-4">
              <p className="mb-3 font-display text-xs tracking-widest text-secondary-foreground">CONTENTS</p>
              {[
                "overview", "features", "backend", "security", "fhe", "vectors", "transformer", "database", "approximation", "model", "code", "trace", "performance", "future",
              ].map((item, index) => (
                <a key={item} href={`#${item}`} className="block border-l border-border px-3 py-1.5 font-mono text-xs uppercase text-muted-foreground transition-colors hover:text-vault-cyan">
                  {String(index + 1).padStart(2, "0")} {item}
                </a>
              ))}
            </div>
          </aside>

          <article className="vault-panel p-5 md:p-8">
            <Section id="overview" title="1. System Overview">
              <p><strong>Architecture.</strong> Vault Infer is a client-side React application with one managed backend function for ML intent classification. The frontend renders the cinematic FHE pipeline, maintains stage state, and invokes the backend only when final classification is required.</p>
              <div className="grid gap-3 md:grid-cols-2">
                {stack.map(([label, value]) => (
                  <div key={label} className="rounded-lg border border-border bg-background/40 p-4">
                    <h3 className="mb-2 text-sm text-secondary-foreground">{label}</h3>
                    <p className="text-sm text-muted-foreground">{value}</p>
                  </div>
                ))}
              </div>
              <p><strong>Deployment assumption.</strong> The repository is configured as a Vite static frontend plus Lovable Cloud backend functions. No Dockerfile, Kubernetes manifest, Flask app, FastAPI app, or Node server process is present.</p>
            </Section>

            <Section id="features" title="2. Feature Breakdown">
              {features.map((feature) => (
                <div key={feature.name} className="rounded-lg border border-border bg-background/40 p-4">
                  <h3 className="mb-2 text-base text-secondary-foreground">{feature.name}</h3>
                  <p><strong>Functionality:</strong> {feature.details}</p>
                  <p><strong>Modules involved:</strong> {feature.modules}</p>
                  <p><strong>Input → processing → output:</strong> {feature.flow}</p>
                </div>
              ))}
            </Section>

            <Section id="backend" title="3. Backend & Server Details">
              <p><strong>Framework.</strong> The backend is a Deno-based HTTP function using the standard <code>serve</code> handler. It is not Flask, FastAPI, Express, or GraphQL.</p>
              <p><strong>API architecture.</strong> REST-style JSON over HTTPS. CORS is handled inside the function with permissive access-control headers and an OPTIONS preflight branch.</p>
              {endpoints.map((endpoint) => (
                <div key={endpoint.path} className="space-y-3 rounded-lg border border-border bg-background/40 p-4">
                  <h3 className="text-base text-secondary-foreground">{endpoint.method} {endpoint.path}</h3>
                  <p>Request schema:</p><CodeBlock>{endpoint.request}</CodeBlock>
                  <p>Response schema:</p><CodeBlock>{endpoint.response}</CodeBlock>
                </div>
              ))}
              <p><strong>Execution flow.</strong> Parse JSON → validate <code>input</code> → read <code>LOVABLE_API_KEY</code> → call AI Gateway chat completion with forced tool call → parse tool arguments → return normalized JSON.</p>
              <p><strong>Concurrency model.</strong> Requests are stateless and event-loop driven. Each invocation performs one outbound model request. No shared mutable memory, queues, database locks, or worker pools are implemented.</p>
            </Section>

            <Section id="security" title="4. Encryption & Security">
              <p><strong>Exact shipped security posture.</strong> The UI demonstrates CKKS-style FHE, but the repository does not include an FHE library, key generator, ciphertext serializer, or client-side decryptor. The ML backend currently receives plaintext input for classification.</p>
              <p><strong>Production target scheme.</strong> CKKS is the correct scheme for approximate real-valued vector inference. AES/RSA would secure transport or key wrapping only; they cannot compute over encrypted vectors.</p>
              <p><strong>Key generation assumption.</strong> A production browser client would generate <code>secretKey</code>, <code>publicKey</code>, <code>relinearizationKeys</code>, and optional <code>galoisKeys</code>. The secret key must never leave the client. The backend receives only public evaluation keys and ciphertexts.</p>
              <p><strong>Workflow.</strong> Text embedding is encoded into CKKS plaintext slots, encrypted client-side, evaluated server-side using supported homomorphic operations, then decrypted client-side into logits or class scores.</p>
            </Section>

            <Section id="fhe" title="5. Fully Homomorphic Encryption (FHE)">
              <p><strong>Scheme.</strong> CKKS over the ring R<sub>q</sub> = ℤ<sub>q</sub>[X] / (X<sup>N</sup> + 1), suitable for approximate arithmetic on real vectors.</p>
              <p><strong>Visualized parameters.</strong> Polynomial modulus degree N = 8192, scale Δ = 2<sup>40</sup>, displayed noise budget ≈ 45 dB decreasing through the encryption stage. Production coefficient modulus would be a chain such as [60, 40, 40, 60] bits.</p>
              <p><strong>Supported operations.</strong> Ciphertext addition, ciphertext-plaintext multiplication, ciphertext-ciphertext multiplication, rescale, relinearize, rotate slots, and polynomial evaluation.</p>
              <p><strong>Noise handling.</strong> Each multiplication increases noise and consumes one modulus level. CKKS uses rescaling after multiplication to restore scale: c′ = round(c / p), q′ = q / p.</p>
            </Section>

            <Section id="vectors" title="6. Vector Processing Pipeline">
              <p><strong>Embedding process.</strong> Input text is tokenized, passed through a sentence transformer, mean-pooled, and normalized to a unit vector e ∈ ℝ<sup>384</sup>.</p>
              <p><strong>Normalization.</strong> For cosine retrieval, ê = e / ||e||₂. Similarity is sim(a,b) = (a · b) / (||a||₂||b||₂). With normalized vectors, cosine similarity reduces to dot product.</p>
              <p><strong>Encrypted handling.</strong> A production FHE pipeline packs the 384 dimensions into CKKS slots. Plaintext model weights can multiply encrypted activations; outputs remain encrypted until client decryption.</p>
            </Section>

            <Section id="transformer" title="7. Sentence Transformer Model">
              <p><strong>Recommended exact model.</strong> <code>sentence-transformers/all-MiniLM-L6-v2</code>. It produces 384-dimensional embeddings and is fast enough for interactive semantic preprocessing.</p>
              <p><strong>Architecture.</strong> MiniLM is a distilled Transformer encoder with 6 layers, hidden size 384, self-attention, WordPiece-style tokenization, mean pooling, and L2 normalization in common sentence-transformers usage.</p>
              <p><strong>Why chosen.</strong> It balances latency, memory footprint, and semantic quality. Its 384-dimensional output aligns with the existing Vault Infer visualization and keeps CKKS ciphertext packing manageable.</p>
              <p><strong>Performance characteristics.</strong> Small model size, low CPU/GPU latency, good general semantic similarity, weaker domain specialization than larger MPNet or E5 models.</p>
              <CodeBlock>{transformerCode}</CodeBlock>
            </Section>

            <Section id="database" title="8. Database / Vector Database Details">
              <p><strong>Current implementation.</strong> The app does not persist documents, embeddings, users, or vectors. No database tables or vector indexes are defined.</p>
              <p><strong>Production design assumption.</strong> Use PostgreSQL with a vector extension for traditional relational metadata plus vector search, or a dedicated vector database such as FAISS, Chroma, Pinecone, or Weaviate.</p>
              <p><strong>Schema and index.</strong> Store one 384-dimensional vector per document. HNSW is recommended for low-latency approximate nearest-neighbor search; Flat indexing is exact but slower at scale; IVF requires training and is more useful for large corpora.</p>
              <CodeBlock>{vectorDbCode}</CodeBlock>
              <p><strong>Query mechanism.</strong> Embed query → normalize → vector nearest-neighbor search → optional rerank → return metadata. For encrypted retrieval, exact practical designs usually combine plaintext public corpora with encrypted query protocols, secure enclaves, or specialized private information retrieval rather than generic CKKS-only ANN.</p>
              <CodeBlock>{queryCode}</CodeBlock>
            </Section>

            <Section id="approximation" title="9. Function Approximation">
              <p><strong>Reason.</strong> FHE supports addition and multiplication efficiently, but not native exponentials, division, softmax, ReLU comparison, or branching. Nonlinear functions must be replaced by low-degree polynomials.</p>
              <p><strong>Displayed function.</strong> σ(x) = 1 / (1 + e<sup>-x</sup>). A practical approximation over x ∈ [-4, 4] could use p₃(x) = 0.5 + 0.25x - x³/48.</p>
              <p><strong>Error assumption.</strong> Cubic sigmoid approximations are cheap but inaccurate at tails. Higher-degree Chebyshev approximations reduce max error ||σ - p||∞ but increase multiplicative depth and noise consumption.</p>
            </Section>

            <Section id="model" title="10. Model Details">
              <p><strong>Shipped classifier.</strong> The backend uses a hosted generative model with tool-constrained JSON output, not a local neural network with repository-stored weights.</p>
              <p><strong>Production encrypted model.</strong> Weights W and bias b are normally plaintext on the evaluator side unless model confidentiality is also required. Inference computes y = W₂ · p(W₁x + b₁) + b₂, where x is encrypted, W and b are plaintext, p is the polynomial activation, and y remains encrypted.</p>
              <p><strong>Storage assumption.</strong> Model weights can be stored as versioned model artifacts or database blobs. If weights are proprietary, use encrypted model serving, multiparty computation, or trusted execution in addition to FHE.</p>
            </Section>

            <Section id="code" title="11. Code-Level Breakdown">
              <p>The following code shows the required production FHE primitives: context creation, key generation, encryption, encrypted computation, and decryption. The current app visualizes these stages but does not execute this cryptographic code.</p>
              <CodeBlock>{fheCode}</CodeBlock>
              <p><strong>Explanation.</strong> Context fixes the ring and modulus chain. Key generation creates client-owned secret material and server evaluation keys. Encoding maps real vectors into CKKS slots. Encryption hides vector values. Homomorphic evaluation computes logits without decrypting. Decryption and decoding happen only on the client.</p>
            </Section>

            <Section id="trace" title="12. Data Flow Trace">
              <ol className="list-decimal space-y-2 pl-6">
                <li><strong>Input:</strong> user writes plaintext in the secure terminal.</li>
                <li><strong>Encoding:</strong> text is represented as tokens and then a sentence embedding.</li>
                <li><strong>Embedding:</strong> all-MiniLM-L6-v2 production target emits e ∈ ℝ³⁸⁴.</li>
                <li><strong>Encryption:</strong> CKKS packs e into slots and encrypts it with the public key.</li>
                <li><strong>Processing:</strong> encrypted linear algebra and polynomial activations produce encrypted logits.</li>
                <li><strong>Decryption:</strong> client secret key decrypts logits and decodes approximate scores.</li>
                <li><strong>Output:</strong> UI displays intent, sentiment, confidence, and natural-language response.</li>
              </ol>
            </Section>

            <Section id="performance" title="13. Performance & Limitations">
              <p><strong>Latency.</strong> Current latency is dominated by frontend animation timing and one remote model call. Production FHE latency would be dominated by CKKS encryption, ciphertext serialization, rotations, multiplications, rescaling, and network transfer of large ciphertexts.</p>
              <p><strong>Memory.</strong> Current memory usage is mostly 3D scene state, canvas binary rain, and React components. Production CKKS ciphertexts can be megabytes each depending on modulus chain and key material.</p>
              <p><strong>Bottlenecks.</strong> Homomorphic rotations, ciphertext-ciphertext multiplication, high-degree polynomial activations, and bootstrapping are the main bottlenecks. The current app does not implement bootstrapping.</p>
              <p><strong>Accuracy vs privacy.</strong> Lower-degree approximations and quantized weights reduce FHE depth and latency but can reduce classifier accuracy. Higher precision increases scale, modulus size, memory, and runtime.</p>
            </Section>

            <Section id="future" title="14. Future Improvements">
              <ul className="list-disc space-y-2 pl-6">
                <li>Replace visualization-only CKKS with a browser-compatible FHE/WebAssembly runtime.</li>
                <li>Add actual all-MiniLM-L6-v2 embedding generation through a dedicated backend embedding endpoint or local WASM inference.</li>
                <li>Add pgvector/HNSW storage for encrypted-pipeline demos over a real corpus.</li>
                <li>Use Chebyshev-minimax polynomial activations and depth-aware model architecture search.</li>
                <li>Add ciphertext serialization telemetry, key lifecycle UI, and reproducible benchmark traces.</li>
                <li>Explore CKKS bootstrapping, TFHE-style programmable bootstrapping, hybrid secure enclaves, or private retrieval protocols for production-grade privacy.</li>
              </ul>
            </Section>
          </article>
        </div>
      </div>
    </main>
  );
}